CREATE DATABASE wpapi;

USE wpapi;

CREATE TABLE IF NOT EXISTS urls(
id INTEGER NOT NULL PRIMARY KEY,
url VARCHAR(200) NOT NULL,
pause INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS responses(
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
id_url INTEGER NOT NULL,
response TEXT,
duration FLOAT,
created_at DATETIME NOT NULL
);